<?php
include './koneksi.php';
$k = new database();

$aksi = $_GET['aksi'];

if ($aksi == "tambahprofile") {
    $nama = $_POST['nama'];
    $username = $_POST['username'];
    $email = $_POST['email'];
    $tgl_lahir = $_POST['tgl_lahir'];
    $jenis_kelamin = $_POST['jenis_kelamin'];
    $no_ponsel = $_POST['no_ponsel'];
    $no_rekening = $_POST['no_rekening'];

    // Check if 'id' is automatically generated by the database
    $id = null; // or set it to the actual value if it's provided

    $result = $k->inputprofile($id, $nama, $username, $email, $tgl_lahir, $jenis_kelamin, $no_ponsel, $no_rekening);

    if ($result) {
        header("Location:../html/daftar-profile.php");
        exit;
    } else {
        // Handle the error, e.g., display a message or redirect to an error page
        echo "Error: Unable to add profile.";
    }
}
?>
